#pragma once
#include "opencv2\\opencv.hpp"
#include "opencv2\\highgui.hpp"
#include <math.h>
#include <vector>
#include <algorithm>
#include <iostream>
#include "algo.h"
#include "ImageProcess.h"
#include "Mouse.h"
#include "VideoProceser.h"